### ISSUE TITLE
No other way to let you know of tourney with live broadcast

### ISSUE THREAD

**Issue by GrahamCCRL** [moterink/Delocto#3]
TOXIC ENVIRONMENT

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
Charlotte 1.0.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 36 rounds
All engines 64-bit 1CPU (where available)

Participants

CM11th Toxic
Fridolin 3.10 64-bit
RookieMonster 0.9.5 64-bit
Zevra 2.5 64-bit
Blunder 7.6.0 64-bit
Odonata 0.5.1 64-bit
Delocto 200419 64-bit
MadChess 3.0 64-bit
Rodin 8.0
Betsabe II 2020

Games and standings will be available after every six rounds from the following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=13746

Web based link for live viewing (huge thanks to Jay - Berserk author).
http://tlcv.net/16094

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16094

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by moterink** [comment]
Hi @GrahamCCRL,

thanks a lot for running those tourneys, it is really appreciated!
However Github Issues should only be used for bug reports or feature requests.
You can write me at talkchess.com anytime though! 🙂

Best regards,
Moritz

**Comment by GrahamCCRL** [comment]
Ok - didn't realize you had an account there.
I'll do that in future. :-)

**Comment by GrahamCCRL** [comment]
*97TH AMATEUR SERIES (Division 7)*

Intel i7-4770k Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ICCF-Pre2022HQ.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit where available

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Odonata 0.6.2 64-bit
Nawito 22.07 64-bit (relegated)
K2 0.99 (relegated)
Devel 4.0.2.3
KnightX 3.4 64-bit (earlier version at author's request)
Blunder 8.5.5 64-bit
Delocto 200419 64-bit
Leorik 2.2 64-bit (promoted)
Lozza 2.4 64-bit
Supernova 2.4 64-bit
Zevra 2.5 64-bit
RookieMonster 1.9.8 64-bit (promoted)


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16092

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16092

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/
